### ISSUE TITLE
Will not work with blueprints with a url_prefix

### ISSUE THREAD

**Issue by jakemwood** [TestBoxLab/chalice-spec#6]

**Comment by knowsuchagency** [comment]
Is it possible to use `chalice-spec` with blueprints?

**Comment by jakemwood** [comment]
We did not build it with this use case in mind, so it’s a bit of an unknown. It might work with blueprints that do not have a `url_prefix`. If you try it please let us know how it goes.

**Comment by jakemwood** [comment]
Believed to be added/fixed as part of #12. Please open a new issue if you have any problems.
